name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential zip unzip git python3-pip \
            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev \
            zlib1g-dev autoconf libtool pkg-config \
            libfreetype6-dev libpng-dev libx11-dev libxcursor-dev \
            libxrandr-dev libxinerama-dev libxi-dev \
            libgl1-mesa-dev libgles2-mesa-dev \
            libgstreamer1.0-0 libgstreamer1.0-dev \
            libmtdev-dev xclip xsel

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install Cython virtualenv
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: kivy-app-apk
          path: bin/*.apk
