name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip
        pip install --upgrade pip setuptools wheel Cython buildozer

    - name: Install buildozer requirements
      run: |
        sudo apt install -y \
          git python3 python3-pip build-essential \
          autoconf automake libtool pkg-config zlib1g-dev \
          libncurses5 libncurses5-dev libstdc++6 \
          libffi-dev libssl-dev libsqlite3-dev libjpeg-dev \
          libandroid-tools adb libgl1-mesa-dev libgles2-mesa-dev

    - name: Initialize buildozer
      run: |
        cd $GITHUB_WORKSPACE
        buildozer init || echo "Already initialized"

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
